### ISSUE TITLE
install failed

### ISSUE THREAD

**Issue by tomjamescn** [JoshuaWise/lzz-gyp#1]
Hi  my env is raspbian jessie on Raspberry Pi 3.
node v6.10.3
npm 3.10.10

when install
I got:
mydir/node_modules/lzz-gyp/lzz-compiled/linux: Syntax error: Unterminated quoted string
Error: exit code 2
    at ChildProcess.<anonymous> (/home/tomjamescn/proxy-ng/node_modules/lzz-gyp/lib/exec.js:19:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

could u help me to solve this problem , thansk very much:)

**Comment by tomjamescn** [comment]
May be this is caused by other module, thank u.
